---
- name: "Add nodejs apt key"
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: "Add nodejs 16.x ppa for apt repo"
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ node_version }}.x focal main'
    update_cache: yes

- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https

- name: Add Yarn apt key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add Yarn repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn

- name: Install dependencies
  apt:
    pkg: "{{ packages }}"
    state: present
    install_recommends: no
    update_cache: yes
  vars:
    packages:
      - libpq5
      - nodejs
      - yarn
      - rsync
      - vim

- name: Move source to server
  synchronize:
    src: ../../
    recursive: yes
    dest: /srv/event-source

- name: Add eventsource group
  group:
    name: '{{ cambiatus_app_group }}'
    gid: '{{ cambiatus_app_gid }}'
    state: present

- name: Add eventsource user
  user:
    name: '{{ cambiatus_app_user }}'
    group: '{{ cambiatus_app_group }}'
    system: yes
    home: '{{ cambiatus_home_dir }}'
    uid: '{{ cambiatus_app_uid }}'
    state: present

- name: Push env vars
  template:
    src: default.j2
    dest: '/etc/default/{{ cambiatus_app_name }}'
    owner: '{{ cambiatus_app_user }}'
    mode: '600'

- name: Create eventsource systemd service file
  template:
    src: service.j2
    dest: '/lib/systemd/system/{{ cambiatus_app_name }}.service'

- name: change owner
  file:
    path: '{{ cambiatus_home_dir }}'
    owner: '{{ cambiatus_app_user }}'
    group: '{{ cambiatus_app_group }}'
    recurse: yes

- name: Enable and start systemd unit
  systemd:
    name: event-source
    state: started
    enabled: yes
    daemon_reload: yes
