#!/usr/bin/env python3
"""Generate the claims id <-> chain id remediation SQL from live data.

    scripts/prod-tunnel.sh up          # read-only tunnel, creds ~/.cambiatus-prod.env
    python3 scripts/build-claims-id-remediation.py > /tmp/claims-remediation.sql

Why a generator and not a checked-in mapping: claims keep arriving, so any static
map goes stale within hours and its UPDATEs then collide with rows created after
it was written. Regenerate immediately before running, review, then run.

How the mapping is derived. Chain claim ids come from one global counter and are
never reused, and `claimaction` does not carry the id -- so when event-source
failed to read the id off chain it fell back to a DB serial and the row landed on
an id that belongs to a DIFFERENT chain claim. The rows are therefore matched on
CONTENT, not on position: (action_id, claimer, proof_photo, proof_code) identifies
a claim directly. Where one claimer filed several claims on one action with the
same proof, the group is matched in ascending id order -- those rows are
indistinguishable by construction, so order preserves creation order.

Do NOT derive this by sequence alignment. Most rows are already correct and the
bad ones are isolated displacements, not a uniform shift, so an alignment that
assumes a shift silently produces a wrong (and non-monotonic) map.
"""

import json
import os
import subprocess
import sys
import urllib.request
from collections import defaultdict

CHAIN_URL = os.environ.get('CHAIN_URL', 'https://app.cambiatus.io')
CONTRACT = os.environ.get('COMMUNITY_CONTRACT', 'cambiatus.cm')
FROM_ID = int(os.environ.get('FROM_ID', '19700'))


def chain_claims():
    """Complete claim set from FROM_ID up, paged on the PRIMARY index.

    nodeos v2.0.7 time-budgets the table walk, so a single call returns a
    nondeterministic prefix with more=true; only the primary index can be
    resumed (next_key is the row id and strictly advances).
    """
    out, lower = {}, FROM_ID
    for _ in range(5000):
        body = json.dumps({"json": True, "code": CONTRACT, "scope": CONTRACT,
                           "table": "claim", "lower_bound": lower, "limit": 1000}).encode()
        req = urllib.request.Request(CHAIN_URL + '/v1/chain/get_table_rows', body,
                                     {"Content-Type": "application/json"})
        res = json.load(urllib.request.urlopen(req, timeout=30))
        for r in res['rows']:
            out[int(r['id'])] = (int(r['action_id']), r['claimer'],
                                 r['proof_photo'], r['proof_code'], r['status'])
        if not res.get('more'):
            return out
        nxt = int(res['next_key'])
        if nxt <= lower:
            sys.exit('next_key did not advance -- cannot page the claim table')
        lower = nxt
    sys.exit('claim snapshot did not terminate')


def db_claims():
    env = {}
    with open(os.path.expanduser('~/.cambiatus-prod.env')) as fh:
        for line in fh:
            if '=' in line and not line.strip().startswith('#'):
                k, _, v = line.strip().partition('=')
                env[k] = v.strip('"\'')
    sql = ("SELECT id, action_id, claimer_id, coalesce(proof_photo,''), "
           "coalesce(proof_code,''), status FROM claims WHERE id >= %d ORDER BY id;" % FROM_ID)
    proc = subprocess.run(
        ['psql', '-h', '127.0.0.1', '-p', env.get('CAMBIATUS_PROD_LOCAL_PORT', '5455'),
         '-U', env['CAMBIATUS_PROD_PG_USER'], '-d', env['CAMBIATUS_PROD_PG_DB'],
         '-At', '-F', '|', '-c', sql],
        capture_output=True, text=True,
        env={**os.environ, 'PGPASSWORD': env['CAMBIATUS_PROD_PG_PASSWORD']})
    if proc.returncode != 0:
        sys.exit('psql failed (is the tunnel up?):\n' + proc.stderr)
    out = {}
    for line in proc.stdout.splitlines():
        p = line.split('|')
        if len(p) >= 6 and p[0].isdigit():
            out[int(p[0])] = (int(p[1]), p[2], p[3], p[4], p[5])
    return out


def main():
    chain, db = chain_claims(), db_claims()

    cidx, dbidx = defaultdict(list), defaultdict(list)
    for cid, v in sorted(chain.items()):
        cidx[v[:4]].append(cid)
    for did, v in sorted(db.items()):
        dbidx[v[:4]].append(did)

    mapping, orphan_db = {}, []
    for key, dids in dbidx.items():
        cids = cidx.get(key, [])
        for n, did in enumerate(dids):
            if n < len(cids):
                mapping[did] = cids[n]
            else:
                orphan_db.append(did)

    renumber = sorted((d, c) for d, c in mapping.items() if d != c)
    backfill = sorted(set(chain) - set(mapping.values()))

    p = print
    p('-- GENERATED by scripts/build-claims-id-remediation.py -- review before running.')
    p('-- chain claims >= %d: %d | db claims >= %d: %d' % (FROM_ID, len(chain), FROM_ID, len(db)))
    p('-- already correct: %d | to renumber: %d | to backfill: %d | db rows with no chain claim: %d'
      % (len(db) - len(renumber), len(renumber), len(backfill), len(orphan_db)))
    if orphan_db:
        p('-- !! DB rows matching no chain claim (investigate, NOT handled here): %s' % orphan_db)
    if not renumber and not backfill:
        p('-- nothing to do.')
        return

    # A target id still held by a row that is not itself being renumbered would
    # violate the PK. Phase 1 parks every moving row above the live id space, so
    # this can only happen if the map is stale -- refuse rather than half-apply.
    moving = {d for d, _ in renumber}
    blocked = [(d, c) for d, c in renumber if c in db and c not in moving]
    if blocked:
        p('-- !! STALE MAP: targets held by non-moving rows: %s' % blocked)
        p('-- Regenerate; do not run.')
        return

    p('\nBEGIN;')
    p('CREATE TEMP TABLE _claim_id_map (old_id bigint PRIMARY KEY, new_id bigint UNIQUE);')
    p('INSERT INTO _claim_id_map VALUES')
    p(',\n'.join('  (%d, %d)' % r for r in renumber) + ';')
    p("""
-- checks / notification_history reference claims.id and the FKs are not
-- deferrable, so drop and re-add them around the renumber. A claim's checks were
-- cast against THAT claim in the app, so they move with it.
ALTER TABLE checks DROP CONSTRAINT checks_claim_id_fkey;
ALTER TABLE notification_history DROP CONSTRAINT notification_history_claim_id_fkey;

-- phase 1: park parents and children above the live id space
UPDATE claims c SET id = c.id + 1000000 FROM _claim_id_map m WHERE c.id = m.old_id;
UPDATE checks k SET claim_id = k.claim_id + 1000000 FROM _claim_id_map m WHERE k.claim_id = m.old_id;
UPDATE notification_history n SET claim_id = n.claim_id + 1000000 FROM _claim_id_map m WHERE n.claim_id = m.old_id;

-- phase 2: land them on their real chain ids
UPDATE claims c SET id = m.new_id FROM _claim_id_map m WHERE c.id = m.old_id + 1000000;
UPDATE checks k SET claim_id = m.new_id FROM _claim_id_map m WHERE k.claim_id = m.old_id + 1000000;
UPDATE notification_history n SET claim_id = m.new_id FROM _claim_id_map m WHERE n.claim_id = m.old_id + 1000000;

ALTER TABLE checks ADD CONSTRAINT checks_claim_id_fkey
  FOREIGN KEY (claim_id) REFERENCES claims(id);
ALTER TABLE notification_history ADD CONSTRAINT notification_history_claim_id_fkey
  FOREIGN KEY (claim_id) REFERENCES claims(id) ON DELETE CASCADE;""")

    if backfill:
        p("""
-- Chain claims that never got a DB row: two claimactions for the same
-- (action, claimer) in ONE transaction, collapsed by claimAction's
-- (created_tx, action_id, claimer_id) dedup guard. created_block/created_tx are
-- not recoverable from table data and stay NULL. Status is the CHAIN status;
-- the votes these claims received were recorded against whichever row held the
-- id at the time, so no checks are synthesised here.""")
        p('INSERT INTO claims (id, action_id, claimer_id, status, proof_photo, proof_code, created_at) VALUES')
        rows = []
        for cid in backfill:
            a, maker, photo, code, status = chain[cid]
            rows.append("  (%d, %d, '%s', '%s', %s, %s, now())"
                        % (cid, a, maker, status,
                           ("'%s'" % photo) if photo else 'NULL',
                           ("'%s'" % code) if code else 'NULL'))
        p(',\n'.join(rows) + ';')

    p("""
SELECT setval('claims_id_seq', (SELECT max(id) FROM claims));

-- ----- verify before COMMIT (every check must hold) -------------------------
-- 0 rows left parked:
SELECT (SELECT count(*) FROM claims WHERE id >= 1000000)
     + (SELECT count(*) FROM checks WHERE claim_id >= 1000000)
     + (SELECT count(*) FROM notification_history WHERE claim_id >= 1000000) AS parked_left;
-- 0 orphaned checks:
SELECT count(*) AS orphan_checks FROM checks k
  WHERE NOT EXISTS (SELECT 1 FROM claims c WHERE c.id = k.claim_id);""")
    p('-- expect %d rows, max id %d:' % (len(db) + len(backfill), max(chain)))
    p('SELECT count(*) AS total, max(id) AS max_id FROM claims WHERE id >= %d;' % FROM_ID)
    p('\n-- ROLLBACK;  -- if anything looks off')
    p('-- COMMIT;    -- only once every check above matches')


if __name__ == '__main__':
    main()
